build: off

os: unstable

platform:
  - x64

branches:
  only:
    - master

skip_tags: true

environment:
  nodejs_version: "8"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm cache verify
  - appveyor-retry npm install
  - npm run build

test_script:
  - node --version
  - npm test
